### ISSUE TITLE
Running PTF tests on Tofino

### ISSUE THREAD

**Issue by antoninbas** [opennetworkinglab/fabric-p4test#10]
The current readme instructions to run PTF tests on Tofino say:
```
sudo ./ptf_runner.py --device tofino \ 
    --p4info p4info.txt \
    --tofino-bin tofino.bin \
    --tofino-ctx-json context.json \
    --ptf-dir fabric.ptf --port-map port_map.veth.json \
    all ^spgw
```
However, I don't think this can realistically work. Updating the P4 program on Tofino will remove the dataplane ports. Maybe we need a `--skip-tests` flag so that the runner can be invoked twice:
```
./ptf_runner.py --skip-tests ....`
// add ports
./ptf_runner.py --skip-config ...`
```
or some other solution...

Maybe I'm missing something @ccascone? How do you run the tests?

**Comment by ccascone** [comment]
You are right, with current instructions tests cannot be executed on Tofino. I agree on adding the `--skip-tests` flag. Another solution could be that of having `ptf_runner.py` configure dataplane ports, but this would require using Tofino APIs.

**Comment by ccascone** [comment]
Added option in #13
